apiVersion: v1
kind: ConfigMap
metadata:
  name: ent-config
  namespace: ent
data:
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "ent-est-sale"
  KEYCLOAK_ADMIN_REALM: "master"
  KEYCLOAK_CLIENT_ID: "ent-backend"
  CASSANDRA_HOST: "cassandra"
  CASSANDRA_PORT: "9042"
  CASSANDRA_KEYSPACE: "ent"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "courses"
  MINIO_SECURE: "false"
  PRESIGNED_URL_EXPIRES_SECONDS: "3600"
